name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.1.1
        with:
          required-ros-distributions: foxy
    
